project:
  type: website
  output-dir: docs

website:
  title: "Data in the Wild, Lewis & Clark"
  navbar: 
    background: primary 
    logo: "images/ditw.png"
    style: "docked"
  sidebar:
    style: "docked"
    collapse-level: 1
    search: false
    contents:
      - href: index.qmd
      - href: using.qmd
      - href: modules.qmd
      - href: content.qmd




      
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: source










