project:
  type: website
  output-dir: docs

website:
  sidebar:
    style: "docked"
    logo: "images/ditw.png"
    collapse-level: 1
    search: false
    contents:
      - href: index.qmd
      - href: using.qmd
      - href: schedule.qmd
      - href: webr-test.qmd



      
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: source
